# Month 1 — NumPy → OpenCV → Mini Computer Vision Pipeline

**Goal:** Move quickly from existing Python familiarity into practical NumPy and OpenCV work.

This notebook is designed as a working notebook, not a lecture.
Use AI as a reviewer/hint provider, but try the exercises yourself first.

**End-of-month target:** build one small, reproducible image-processing pipeline and document the experiments.

## How to use this notebook

1. Read the short concept note.
2. Run the tiny example.
3. Close the example and solve the exercise yourself.
4. Only then use AI to review/debug.
5. Record what you learned in the experiment sections.
6. Commit useful work to GitHub.

## Week 1 — NumPy Core

You already know basic Python, so we will not restart from variables/loops.
We will focus on the parts that matter for computer vision:

- arrays
- shape / ndim / dtype
- indexing and slicing
- boolean masking
- reshape / transpose
- concatenation / stacking
- broadcasting
- vectorized operations
- basic statistics
- image-like arrays

In [2]:
from random import random
from typing import cast

import numpy as np
from PIL.ImageOps import grayscale
from numpy.ma.core import size

a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("ndim:", a.ndim)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
ndim: 1
dtype: int64


### Exercise 1 — Inspect an array

Create an array containing 10 numbers and print:

- the array
- shape
- ndim
- dtype
- mean
- standard deviation

In [13]:
arr=np.array([12,13,46,45,67,78,89,32,96,10])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.mean())
print(f"{arr.std():.2f}")

[12 13 46 45 67 78 89 32 96 10]
(10,)
1
int64
48.8
30.78


### Exercise 2 — 2D arrays

Create a 3×4 array.

Then:

- select the second row
- select the third column
- select the top-left 2×2 region

In [25]:
arr=np.random.randint(1,100,size=(3,4))
print(arr)
arr[:,2]
arr[:2,:2]


[[92 39 28 31]
 [51 39  6  1]
 [30 60 93 91]]


array([[92, 39, 28],
       [51, 39,  6],
       [30, 60, 93]], dtype=int32)

### Exercise 3 — Boolean masking

Create an array of 20 values.

Select values that are:

- greater than the mean
- less than 10

Do this with boolean masks, not a Python loop.

In [33]:
arr=np.random.randint(1,100,size=20)
mean_a=arr.mean()
arr[arr > mean_a]

arr[arr<10]

array([8, 9], dtype=int32)

### 1D
- arr[i]
- arr[start:end]
- arr[:n]
- arr[-n:]
- arr[condition]

### 2D
- arr[row, col]
- arr[row]
- arr[:, col]
- arr[row, :]
- arr[r1:r2, c1:c2]

### 3D
- arr[depth, row, col]
- arr[:, row, col]
- arr[depth, :, :]
- arr[:, :, col]

### Boolean
- arr[arr > 80]
- arr[(arr > 70) & (arr < 90)]
- arr[(arr > 90) | (arr < 60)]

In [43]:
# ============================================================
# NUMPY INDEXING DRILL
# ============================================================

import numpy as np

# ------------------------------------------------------------
# 1D ARRAY
# ------------------------------------------------------------

arr1 = np.arange(1, 21)

print("arr1:")
print(arr1)

# TODO 1
# İlk 5 elemanı seç.
print(arr1[:5])

# TODO 2
# Son 4 elemanı seç.
print(arr1[-4:])

# TODO 3
# Index 5 ile index 12 arasındaki elemanları seç.
# 5 dahil, 12 hariç.
print(arr1[5:12])

# TODO 4
# Baştan başlayarak 2'şer atlayarak elemanları seç.
print(arr1[::2])

# TODO 5
# 10'dan büyük elemanları seç.
print(arr1[arr1>10])

# TODO 6
# 5 ile 15 arasındaki elemanları seç.
# 5 ve 15 dahil.
print(arr1[(arr1>=5)&(arr1<=15)])




arr1:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]
[17 18 19 20]
[ 6  7  8  9 10 11 12]
[ 1  3  5  7  9 11 13 15 17 19]
[11 12 13 14 15 16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [59]:
# ------------------------------------------------------------
# 2D ARRAY
# ------------------------------------------------------------

arr2 = np.arange(1, 25).reshape(4, 6)

print("\narr2:")
print(arr2)

# TODO 7
# İlk satırı seç.
arr2[:5]

# TODO 8
# Son satırı seç.
arr2[-1:]

# TODO 9
# 2. satırı seç. (index = 1)
arr2[1,:]

# TODO 10
# İlk sütunu seç.
arr2[:,1]

# TODO 11
# Son sütunu seç.
arr2[:,-1]

# TODO 12
# İlk 2 satırı seç.
arr2[:2,:]

# TODO 13
# 2. ve 3. sütunları seç. (index 1 ve 2)
arr2[:,1:3]

# TODO 14
# İlk 3 satır + ilk 4 sütunu seç.
arr2[:3,:4]

# TODO 15
# 2. satırdan son satıra kadar + son 3 sütunu seç.
arr2[2:,-3:]

# TODO 16
# Çift indexli satırları seç.
##even=lambda x: x if x%2==0 else None
arr2[0::2,:]

# TODO 17
# Tek indexli sütunları seç.
arr2[1::2,:]

# TODO 18
# 15'ten büyük tüm değerleri seç.
arr2[arr2>15]


arr2:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


array([16, 17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
# ------------------------------------------------------------
# 2D BOOLEAN MASKING
# ------------------------------------------------------------

# TODO 19
# 10'dan büyük VE 20'den küçük değerleri seç.
arr2[(arr2>10)&(arr2<20)]

# TODO 20
# 5'ten küçük VEYA 20'den büyük değerleri seç.
arr2[(arr2<5) | (arr2>20)]

array([ 1,  2,  3,  4, 21, 22, 23, 24])

In [70]:
# ------------------------------------------------------------
# SHAPE DRILL
# ------------------------------------------------------------

# Aşağıdakilerin shape'lerini ÖNCE TAHMİN ET,
# sonra print ederek kontrol et.

# TODO 21
# arr2[0]
# shape (1,1)
arr2[0].shape
#(6,)

# TODO 22
# arr2[0:1]
#shape (2,2)
arr2[0:1].shape
#(1, 6)

# TODO 23
# arr2[:, 0]
#shape (4,1)
arr2[:, 0].shape
#(4,)

# TODO 24
# arr2[:, 0:1]
#shape (4,0)
arr2[:, 0:1].shape
#(4, 1)

# TODO 25
# arr2[1:3, 2:5]
#shape (2,3)
arr2[1:3, 2:5].shape
#(2,3)



"""
[0]    → tek eleman / tek satır / tek sütun → boyut düşebilir
[0:1]  → slice → boyut korunur
"""


array([1, 2, 3, 4, 5, 6])

In [80]:
# ------------------------------------------------------------
# 3D ARRAY
# ------------------------------------------------------------

arr3 = np.arange(1, 61).reshape(3, 4, 5)

print("\narr3 shape:")
print(arr3.shape)

# Shape:
# depth = 3
# rows  = 4
# columns = 5

# TODO 26
# İlk 2D bloğu seç.
arr3[0,:,:]

# TODO 27
# İkinci depth bloğunu seç.
arr3[1,:,:]


# TODO 28
# Bütün depth'lerde ilk satırı seç.
arr3[:,0,:]

# TODO 29
# Bütün depth'lerde ilk sütunu seç.
arr3[:,:,0]

# TODO 30
# Tüm depth'lerde 2. ve 3. sütunları seç.
arr3[:,:,1:3]

# TODO 31
# İlk 2 depth'i seç.
arr3[0:2,:,:]

# TODO 32
# İlk 2 depth + ilk 2 satır + son 3 sütunu seç.
arr3[0:2,0:2,-3:]



arr3 shape:
(3, 4, 5)


array([[[ 3,  4,  5],
        [ 8,  9, 10]],

       [[23, 24, 25],
        [28, 29, 30]]])

In [93]:
# ------------------------------------------------------------
# FINAL SHAPE CHALLENGE
# ------------------------------------------------------------

# Her biri için:
# 1) Önce shape'i tahmin et
# 2) Sonra print et

# TODO 33
result1 = arr3[:, :, 0]
#shape (3,4,)
##(3, 4)

# TODO 34
result2 = arr3[:, 1, :]
#shape (3,1,5)
##(3,5)

# TODO 35
result3 = arr3[0:2, :, 1:4]
#shape (2,4,3)
##(2, 4, 3)

# TODO 36
result4 = arr3[:, 0:2, :]
#shape (3,2,5)
##(3,2,5)

# TODO 37
result5 = arr3[1:, 1:3, 2:]
#shape (2,2,3)
##(2,2,3)

print(result1.shape)
print(result2.shape)
print(result3.shape)
print(result4.shape)
print(result5.shape)

(3, 4)
(3, 5)
(2, 4, 3)
(3, 2, 5)
(2, 2, 3)


### Exercise 4 — Reshape and transpose

Create a 1D array containing 12 values.

1. Reshape it to 3×4.
2. Transpose it.
3. Print the shape before and after.

In [108]:
# Your solution
#arr_r=np.random.randint(1,100,size=(12))
arr_r=np.arange(1,13)
arr_t=arr_r.reshape(3,4).T
print(arr_r)
print(arr_t)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Exercise 5 — Broadcasting

Create:

- a 3×3 array
- a 1D array with 3 values

Add them together using NumPy broadcasting.
Then explain in one sentence why it works.

In [110]:
# Your solution
arr_a=np.arange(1,10).reshape(3,-1)
arr_b=np.array([1,2,3])
arr_c=arr_a+arr_b
arr_c

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

### Exercise 6 — Image-like data

An RGB image can be represented as an array with shape:

`(height, width, channels)`

Create a fake image with shape `(100, 150, 3)`.
Inspect:

- shape
- dtype
- minimum value
- maximum value
- mean

In [118]:
# Your solution
image=np.random.randint(1,256,size=(10,150,3),dtype=np.uint8)
image.shape
image.dtype
image.min()
image.max()
image.mean()


np.float64(127.846)

## Week 1 — No-AI Challenge

Close the examples above.

Write a small NumPy program from an empty cell that:

1. creates a random RGB-like image
2. converts it to grayscale using a simple channel average
3. prints the original and grayscale shapes

Do not ask AI for code before your first attempt.

In [123]:
# No-AI challenge
arr_rgb=np.random.randint(0,255,(10,150,3),dtype=np.uint8)
grayscale=arr_rgb.mean(axis=2)
print(grayscale.shape)
print(arr_rgb.shape)

(10, 150)
(10, 150, 3)


## Week 2 — NumPy for Images + OpenCV

Core OpenCV tools:

- `cv2.imread`
- `cv2.imwrite`
- `cv2.cvtColor`
- `cv2.resize`
- cropping
- drawing
- grayscale
- BGR / RGB awareness

In [10]:
import cv2

from pathlib import Path

print("OpenCV version:", cv2.__version__)

ModuleNotFoundError: No module named 'cv2'

### Exercise 7 — Load an image

Put an image in the same folder as this notebook, then load it.

Print:

- whether loading succeeded
- shape
- dtype

In [ ]:
# Example:
# image = cv2.imread("your_image.jpg")

# Your solution

### Exercise 8 — Grayscale, resize, crop

For one image:

1. create a grayscale version
2. resize it to half width and half height
3. crop the center region
4. save all three outputs

In [ ]:
# Your solution

### Exercise 9 — Draw on an image

Make a copy of the image.

Draw:

- one rectangle
- one line
- one circle

Save the result separately so the original is preserved.

In [ ]:
# Your solution

## Week 3 — Image Processing

Topics:

- Gaussian blur
- thresholding
- adaptive thresholding
- Canny edges
- erosion / dilation
- opening / closing
- masks
- contours
- bounding rectangles

In [ ]:
# Start with an image loaded as `image`.
# If needed, uncomment and edit:
# image = cv2.imread("your_image.jpg")

gray = None

# Your code here

### Exercise 10 — Blur experiment

Try at least three Gaussian blur kernel sizes.

Record:

- kernel size
- what you expected
- what you observed

In [ ]:
# Your experiment

### Experiment Log

| Experiment | Parameters | Expectation | Observed Result | Next Change |
|---|---|---|---|---|
| 1 |  |  |  |  |
| 2 |  |  |  |  |
| 3 |  |  |  |  |

### Exercise 11 — Canny edge detection

Run Canny with at least two parameter settings.

Compare the results and explain which setting produced a more useful edge map.

In [ ]:
# Your solution

### Exercise 12 — Thresholding

Create a binary mask from a grayscale image.

Then compare the mask before and after a small amount of morphology.

In [ ]:
# Your solution

### Exercise 13 — Contours

Find contours in your binary image.

For each useful contour, try to:

- draw it
- compute its bounding rectangle
- calculate its area

In [ ]:
# Your solution

## Week 4 — Mini Computer Vision Pipeline

### Project: Architectural Image Processing Pipeline

Use 5–10 architectural images.

Pipeline:

`input folder`
→ `load`
→ `validate`
→ `resize / normalize`
→ `grayscale`
→ `blur`
→ `edge detection`
→ `threshold / mask`
→ `contours`
→ `save outputs`

The goal is not visual beauty.
The goal is a reproducible pipeline that you understand and can explain.

In [ ]:
from pathlib import Path
import cv2
import numpy as np

INPUT_DIR = Path("input_images")
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

# 1. list images
# 2. load each image
# 3. process
# 4. save results

# Start here.

### Pipeline checklist

- [ ] Input files are validated.
- [ ] The script handles a missing/broken image gracefully.
- [ ] Output files are written to a separate directory.
- [ ] Parameters are easy to change.
- [ ] The pipeline can process multiple images.
- [ ] I can explain every major step.

## R&D Experimentation

For one processing step, test at least three parameter choices.

Example:

- Canny thresholds
- blur kernel size
- threshold value
- morphology kernel size

Do **not** change five things at once.

Record the result and your hypothesis.

In [ ]:
# Experiment template

experiment = {
    "parameter": "",
    "baseline": "",
    "new_value": "",
    "hypothesis": "",
    "result": "",
    "next_step": "",
}

experiment

## Debugging Practice

When something breaks, use this order:

1. Read the error.
2. Identify the exact line.
3. Inspect the input type/shape/value.
4. Reduce the problem to the smallest failing case.
5. Fix it.
6. Run again.
7. Only then ask AI for help if needed.

Do not paste a large unknown solution into the project.

## AI-Assisted Coding Rule

**First attempt:** write it yourself.

**Second step:** ask AI for a hint or explanation.

**Third step:** compare your code with the suggestion.

**Final step:** rewrite the part you now understand.

The goal is not zero AI use.
The goal is **zero black-box code**.

## Technical English — 10–20 minutes

After each session, explain what you did using short sentences.

Useful patterns:

- “The goal was to…”
- “I started by…”
- “The input was…”
- “I changed…”
- “The result was…”
- “The main problem was…”
- “I tested two different settings.”
- “The second approach worked better because…”
- “Next, I would…”

In [ ]:
# Speaking notes — fill these in after today's work.

goal = ""
what_i_did = ""
problem = ""
result = ""
next_step = ""

print("The goal was to", goal)
print("I started by", what_i_did)
print("The main problem was", problem)
print("The result was", result)
print("Next, I would", next_step)

## End-of-Month Self Check

Mark each item only when you can do it with little or no AI assistance.

- [ ] Create and inspect NumPy arrays.
- [ ] Use shape, slicing and masking comfortably.
- [ ] Explain an image as an array.
- [ ] Load/edit/save images with OpenCV.
- [ ] Apply thresholding and Canny.
- [ ] Create a mask.
- [ ] Find and draw contours.
- [ ] Debug a small Python image-processing script.
- [ ] Process a folder of images.
- [ ] Compare experiments and record observations.
- [ ] Explain the mini-project in English.
- [ ] Push the project to GitHub with a useful README.

## End-of-Month Deliverables

1. **One GitHub repository**
2. **One reproducible image-processing pipeline**
3. **At least 3 documented experiments**
4. **Short technical English explanation**
5. **One README with problem, approach, results and limitations**

### Next Month

Month 2 moves into:

**Dataset handling → PyTorch tensors → Dataset/DataLoader → training loop → classification → detection → segmentation → evaluation**